CC = gcc
CFLAGS = -I.



default: 
	$(CC) main.c vec2.c drone.c comms.c -std=c99 -o ./build/vocabs2.exe -lm -Wall -Wfatal-errors -Wextra -fopenmp -finline-functions

clean:
	rm ./build/*.*

