from subprocess import run

run(["./build/vocabs2.exe", "A"])
run(["./build/vocabs2.exe", "C"])
run(["./build/vocabs2.exe", "E"])
run(["./build/vocabs2.exe", "A", "0.5"])
run(["./build/vocabs2.exe", "C", "0.5"])
run(["./build/vocabs2.exe", "E", "0.5"])
run(["./build/vocabs2.exe", "A", "1"])
run(["./build/vocabs2.exe", "C", "1"])
run(["./build/vocabs2.exe", "E", "1"])
run(["./build/vocabs2.exe", "A", "1.5"])
run(["./build/vocabs2.exe", "C", "1.5"])
run(["./build/vocabs2.exe", "E", "1.5"])
run(["./build/vocabs2.exe", "A", "2"])
run(["./build/vocabs2.exe", "C", "2"])
run(["./build/vocabs2.exe", "E", "2"])
run(["./build/vocabs2.exe", "A", "2.5"])
run(["./build/vocabs2.exe", "C", "2.5"])
run(["./build/vocabs2.exe", "E", "2.5"])
run(["./build/vocabs2.exe", "A", "3"])
run(["./build/vocabs2.exe", "C", "3"])
run(["./build/vocabs2.exe", "E", "3"])
run(["./build/vocabs2.exe", "A", "3.5"])
run(["./build/vocabs2.exe", "C", "3.5"])
run(["./build/vocabs2.exe", "E", "3.5"])
run(["./build/vocabs2.exe", "A", "4"])
run(["./build/vocabs2.exe", "C", "4"])
run(["./build/vocabs2.exe", "E", "4"])
run(["./build/vocabs2.exe", "A", "5"])
run(["./build/vocabs2.exe", "C", "5"])
run(["./build/vocabs2.exe", "E", "5"])
